const collection = [
  {
    disciplineTitle: 'Fine Art',
    disciplineName: 'Fine_Art',
    collectionTitle: 'Mythologies',
    collectionName: 'Mythologies',
     images: [
      { title: 'Sanguine Miles', name: 'Sanguine_Miles', path: '/gallery/Mythologies/Sanguine_Miles', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Valteri Mortem Benjamin', name: 'Valteri_Mortem_Benjamin', path: '/gallery/Mythologies/Valteri_Mortem_Benjamin', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Turris Babel', name: 'Turris_Babel', path: '/gallery/Mythologies/Turris_Babel', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Regina Sumer', name: 'Regina_Sumer', path: '/gallery/Mythologies/Regina_Sumer', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Natalis Sancti Igne', name: 'Natalis_Sancti_Igne', path: '/gallery/Mythologies/Natalis_Sancti_Igne', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Caput Corpori Mutationes Autem Perseus', name: 'Caput_Corpori_Mutationes_Autem_Perseus', path: '/gallery/Mythologies/Caput_Corpori_Mutationes_Autem_Perseus', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Parere BeBop II', name: 'Parere_BeBop_II', path: '/gallery/Mythologies/Parere_BeBop_II', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Poster Tabula I', name: 'Poster_Tabula_I', path: '/gallery/Mythologies/Poster_Tabula_I', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Atlas Tenebre', name: 'Atlas_Tenebre', path: '/gallery/Mythologies/Atlas_Tenebre', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Anisoptera', name: 'Anisoptera', path: '/gallery/Mythologies/Anisoptera', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Innare Carinas Lumen Reflexa', name: 'Innare_Carinas_Lumen_Reflexa', path: '/gallery/Mythologies/Innare_Carinas_Lumen_Reflexa', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Obumbratio', name: 'Obumbratio', path: '/gallery/Mythologies/Obumbratio', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Bis Flores Exploded', name: 'Bis_Flores_Exploded', path: '/gallery/Mythologies/Bis_Flores_Exploded', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Ambustam Lign Glacialis Aquae', name: 'Ambustam_Lign_Glacialis_Aquae', path: '/gallery/Mythologies/Ambustam_Lign_Glacialis_Aquae', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Mulier Cyclopis', name: 'Mulier_Cyclopis', path: '/gallery/Mythologies/Mulier_Cyclopis', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Parere BeBop I', name: 'Parere_BeBop_I', path: '/gallery/Mythologies/Parere_BeBop_I', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Pisces Quoque Aurum', name: 'Pisces_Quoque_Aurum', path: '/gallery/Mythologies/Pisces_Quoque_Aurum', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'O Inaestimabilis Pax Americana', name: 'O_Inaestimabilis_Pax_Americana', path: '/gallery/Mythologies/O_Inaestimabilis_Pax_Americana', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Venit Stercore', name: 'Venit_Stercore', path: '/gallery/Mythologies/Venit_Stercore', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Musae in Deliquium', name: 'Musae_in_Deliquium', path: '/gallery/Mythologies/Musae_in_Deliquium', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Capulus Tabernum', name: 'Capulus_Tabernum', path: '/gallery/Mythologies/Capulus_Tabernum', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Claviaturae', name: 'Claviaturae', path: '/gallery/Mythologies/Claviaturae', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Ones Tenebris Flavaque', name: 'Ones_Tenebris_Flavaque', path: '/gallery/Mythologies/Ones_Tenebris_Flavaque', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
      { title: 'Convallaria Majalis', name: 'Convallaria_Majalis', path: '/gallery/Mythologies/Convallaria_Majalis', ratio: '1:1', year: '2018', tags: 'Digital Photography, Pixellation' },
    ]
  },
  {
    disciplineTitle: 'Fine Art',
    disciplineName: 'Fine_Art',
    collectionTitle: 'Nature Morté',
    collectionName: 'Nature_Morte',
   images: [
      { title: '1 - The Creative - 63', name: '1_The_Creative_63', path: '/gallery/Nature_Morte/1_The_Creative_63', ratio: '1:1', year: '2011', tags: 'Digital Photography, Still Life' },
      { title: '24 - Return - 1', name: '24_Return_1', path: '/gallery/Nature_Morte/24_Return_1', ratio: '1:1', year: '2011', tags: 'Digital Photography, Still Life' },
      { title: '64 - Before Completion - 42', name: '64_Before_Completion_42', path: '/gallery/Nature_Morte/64_Before_Completion_42', ratio: '1:1', year: '2011', tags: 'Digital Photography, Still Life' },
      { title: '2 - The Receptive - 0', name: '2_The_Receptive_0', path: '/gallery/Nature_Morte/2_The_Receptive_0', ratio: '1:1', year: '2013', tags: 'Digital Photography, Still Life' },
      { title: '5 - Nourishing While Waiting - 23', name: '5_Nourishing_While_Waiting_23', path: '/gallery/Nature_Morte/5_Nourishing_While_Waiting_23', ratio: '1:1', year: '2012', tags: 'Digital Photography, Still Life' },
      { title: '18 - Decay - 38', name: '18_Decay_38', path: '/gallery/Nature_Morte/18_Decay_38', ratio: '1:1', year: '2012', tags: 'Digital Photography, Still Life' },
      { title: '40 - Limitation - 10', name: '40_Limitation_10', path: '/gallery/Nature_Morte/40_Limitation_10', ratio: '1:1', year: '2012', tags: 'Digital Photography, Still Life' },
      { title: '9 - Small Restraint - 55', name: '9_Small_Restraint_55', path: '/gallery/Nature_Morte/9_Small_Restraint_55', ratio: '1:1', year: '2011', tags: 'Digital Photography, Still Life' },
      { title: '37 - Family - 53', name: '37_Family_53', path: '/gallery/Nature_Morte/37_Family_53', ratio: '1:1', year: '2018', tags: 'Digital Photography, Still Life' },
      { title: '23 - Split Apart - 32', name: '23_Split_Apart_32', path: '/gallery/Nature_Morte/23_Split_Apart_32', ratio: '1:1', year: '2011', tags: 'Digital Photography, Still Life' },
      { title: '46 - Pushing Upward - 6', name: '46_Pushing_Upward_6', path: '/gallery/Nature_Morte/46_Pushing_Upward_6', ratio: '1:1', year: '2013', tags: 'Digital Photography, Still Life' },
      { title: '59 - Dispersion - 50', name: '59_Dispersion_50', path: '/gallery/Nature_Morte/59_Dispersion_50', ratio: '1:1', year: '2011', tags: 'Digital Photography, Still Life' },
    ]
  },
  {
    disciplineTitle: 'Fine Art',
    disciplineName: 'Fine_Art',
    collectionTitle: 'Starlight Meadows',
    collectionName: 'Starlight_Meadows',
    images: [
      { title: 'This Is Not An Abattoir', name: 'This_Is_Not_An_Abattoir', path: '/gallery/Starlight_Meadows/This_Is_Not_An_Abattoir', ratio: '3:2', year: '2005', tags: 'Digital Photography, Directorial' },
      { title: 'Wait A Minute We’re the Good Guys?', name: 'Wait_A_Minute_Were_the_Good_Guys', path: '/gallery/Starlight_Meadows/Wait_A_Minute_Were_the_Good_Guys', ratio: '3:2', year: '2006', tags: 'Digital Photography, Directorial' },
      { title: 'We Do Not Torture People', name: 'We_Do_Not_Torture_People', path: '/gallery/Starlight_Meadows/We_Do_Not_Torture_People', ratio: '3:2', year: '2005', tags: 'Digital Photography, Directorial' },
      { title: 'Media Bias: Axis of Evil', name: 'Media_Bias_Axis_of_Evil', path: '/gallery/Starlight_Meadows/Media_Bias_Axis_of_Evil', ratio: '3:2', year: '2005',  tags:'Digital Photography, Directorial' },
      { title: 'The King Is with Us Now', name: 'The_King_Is_with_Us_Now', path: '/gallery/Starlight_Meadows/The_King_Is_with_Us_Now', ratio: '3:2', year: '2005', tags: 'Digital Photography, Directorial' },
      { title: 'Mr. Halloween', name: 'Mr_Halloween', path: '/gallery/Starlight_Meadows/Mr_Halloween', ratio: '3:2', year: '2005',  tags:'Digital Photography, Directorial' },
      { title: 'On the Seventh of November', name: 'On_the_Seventh_of_November', path: '/gallery/Starlight_Meadows/On_the_Seventh_of_November', ratio: '3:2', year: '2005', tags: 'Digital Photography, Directorial' },
      { title: 'Captured by the Pigs', name: 'Captured_by_the_Pigs', path: '/gallery/Starlight_Meadows/Captured_by_the_Pigs', ratio: '3:2', year: '2005', tags: 'Digital Photography, Directorial' },
      { title: 'Guerilla Warfare', name: 'Guerilla_Warfare', path: '/gallery/Starlight_Meadows/Guerilla_Warfare', ratio: '3:2', year: '2006', tags: 'Digital Photography, Directorial' },
      { title: 'A Life That Lasts a Day', name: 'A_Life_That_Lasts_a_Day', path: '/gallery/Starlight_Meadows/A_Life_That_Lasts_a_Day', ratio: '3:2', year: '2005', tags: 'Digital Photography, Directorial' },
      { title: 'The Watchman', name: 'The_Watchman', path: '/gallery/Starlight_Meadows/The_Watchman', ratio: '3:2', year: '2005', tags: 'Digital Photography, Directorial' },
      { title: 'Remember—Remember—The Seventh of November', name: 'Remember_Remember_The_Seventh_of_November', path: '/gallery/Starlight_Meadows/Remember_Remember_The_Seventh_of_November', ratio: '3:2', year: '2006', tags: 'Digital Photography, Directorial' },
      { title: 'Yule', name: 'Yule', path: '/gallery/Starlight_Meadows/Yule', ratio: '3:2', year: '2005',  tags: 'Digital Photography, Directorial' },
      { title: 'He Is with Us but Remembers Nothing', name: 'He_Is_with_Us_but_Remembers_Nothing', path: '/gallery/Starlight_Meadows/He_Is_with_Us_but_Remembers_Nothing', ratio: '3:2', year: '2005', tags: 'Digital Photography, Directorial' },
      { title: 'He Was Looking for a Way Out', name: 'He_Was_Looking_for_a_Way_Out', path: '/gallery/Starlight_Meadows/He_Was_Looking_for_a_Way_Out', ratio: '3:2', year: '2005', tags: 'Digital Photography, Directorial' },
      { title: 'Troglodytes, They were Called', name: 'Troglodytes_They_were_Called', path: '/gallery/Starlight_Meadows/Troglodytes_They_were_Called', ratio: '3:2', year: '2005', tags: 'Digital Photography, Directorial' },
      { title: 'That Old Chimp Called Himself Sarge', name: 'That_Old_Chimp_Called_Himself_Sarge', path: '/gallery/Starlight_Meadows/That_Old_Chimp_Called_Himself_Sarge', ratio: '3:2', year: '2005', tags: 'Digital Photography, Directorial' },
      { title: 'You Didn’t—But, I Did.', name: 'You_Didnt_But_I_Did', path: '/gallery/Starlight_Meadows/You_Didnt_But_I_Did', ratio: '3:2', year: '2005', tags: 'Digital Photography, Directorial' },
      { title: 'Behind the Barn', name: 'Behind_the_Barn', path: '/gallery/Starlight_Meadows/Behind_the_Barn', ratio: '3:2', year: '2005', tags: 'Digital Photography, Directorial' },
      { title: 'That’s No Way to Play', name: 'Thats_No_Way_to_Play', path: '/gallery/Starlight_Meadows/Thats_No_Way_to_Play', ratio: '3:2', year: '2006', tags: 'Digital Photography, Directorial' },
    ]
  }
  
]

export default collection
