const collection = {
  Mythologies: {
    collectionTitle: 'Mythologies',
    collectionName: 'Mythologies',
    images: [
      { title: 'Sanguine Miles', name: 'Sanguine_Miles', as: '/gallery/Mythologies/Sanguine_Miles', ratio: '1:1' },
      { title: 'Valteri Mortem Benjamin', name: 'Valteri_Mortem_Benjamin', as: '/gallery/Mythologies/Valteri_Mortem_Benjamin', ratio: '1:1' },
      { title: 'Turris Babel', name: 'Turris_Babel', as: '/gallery/Mythologies/Turris_Babel', ratio: '1:1' },
      { title: 'Regina Sumer', name: 'Regina_Sumer', as: '/gallery/Mythologies/Regina_Sumer', ratio: '1:1' },
      { title: 'Natalis Sancti Igne', name: 'Natalis_Sancti_Igne', as: '/gallery/Mythologies/Natalis_Sancti_Igne', ratio: '1:1' },
      { title: 'Perseus Caput Corpori Adiecta Mutationes', name: 'Perseus_Caput_Corpori_Adiecta_Mutationes', as: '/gallery/Mythologies/Perseus_Caput_Corpori_Adiecta_Mutationes', ratio: '1:1' },
      { title: 'Parere BeBop II', name: 'Parere_BeBop_II', as: '/gallery/Mythologies/Parere_BeBop_II', ratio: '1:1' },
      { title: 'Poster Tabula I', name: 'Poster_Tabula_I', as: '/gallery/Mythologies/Poster_Tabula_I', ratio: '1:1' },
      { title: 'Atlas Tenebre', name: 'Atlas_Tenebre', as: '/gallery/Mythologies/Atlas_Tenebre', ratio: '1:1' },
      { title: 'Anisoptera', name: 'Anisoptera', as: '/gallery/Mythologies/Anisoptera', ratio: '1:1' },
      { title: 'Innare Carinas Lumen Reflexa', name: 'Innare_Carinas_Lumen_Reflexa', as: '/gallery/Mythologies/Innare_Carinas_Lumen_Reflexa', ratio: '1:1' },
      { title: 'Obumbratio', name: 'Obumbratio', as: '/gallery/Mythologies/Obumbratio', ratio: '1:1' },
      { title: 'Bis Flores Exploded', name: 'Bis_Flores_Exploded', as: '/gallery/Mythologies/Bis_Flores_Exploded', ratio: '1:1' },
      { title: 'Ambustam Lign Glacialis Aquae', name: 'Ambustam_Lign_Glacialis_Aquae', as: '/gallery/Mythologies/Ambustam_Lign_Glacialis_Aquae', ratio: '1:1' },
      { title: 'Mulier Cyclopis', name: 'Mulier_Cyclopis', as: '/gallery/Mythologies/Mulier_Cyclopis', ratio: '1:1' },
      { title: 'Parere BeBop I', name: 'Parere_BeBop_I', as: '/gallery/Mythologies/Parere_BeBop_I', ratio: '1:1' },
      { title: 'Pisces Quoque Aurum', name: 'Pisces_Quoque_Aurum', as: '/gallery/Mythologies/Pisces_Quoque_Aurum', ratio: '1:1' },
      { title: 'O Inaestimabilis Pax Americana', name: 'O_Inaestimabilis_Pax_Americana', as: '/gallery/Mythologies/O_Inaestimabilis_Pax_Americana', ratio: '1:1' },
      { title: 'Venit Stercore', name: 'Venit_Stercore', as: '/gallery/Mythologies/Venit_Stercore', ratio: '1:1' },
      { title: 'Musae in Deliquium', name: 'Musae_in_Deliquium', as: '/gallery/Mythologies/Musae_in_Deliquium', ratio: '1:1' },
      { title: 'Capulus Tabernum', name: 'Capulus_Tabernum', as: '/gallery/Mythologies/Capulus_Tabernum', ratio: '1:1' },
      { title: 'Claviaturae', name: 'Parere_BeBop_I', as: '/gallery/Mythologies/Parere_BeBop_I', ratio: '1:1' },
      { title: 'Ones Tenebris Flavaque', name: 'Ones_Tenebris_Flavaque', as: '/gallery/Mythologies/Ones_Tenebris_Flavaque', ratio: '1:1' },
      { title: 'Convallaria Majalis', name: 'Convallaria_Majalis', as: '/gallery/Mythologies/Convallaria_Majalis', ratio: '1:1' },
    ]
  },
  Nature_Morte: {
    collectionTitle: 'Nature Morte',
    collectionName: 'Nature_Morte',
    images: [
      { title: '1 - The Creative - 63', name: '1_-_The_Creative_-_63', as: '/gallery/Nature_Morte/1_-_The_Creative_-_63', ratio: '1:1' },
      { title: '24 - Return - 1', name: '24_-_Return_-_1', as: '/gallery/Nature_Morte/24_-_Return_-_1', ratio: '1:1' },
      { title: '64 - Before Completion - 42', name: '64_-_Before_Completion_-_42', as: '/gallery/Nature_Morte/64_-_Before_Completion_-_42', ratio: '1:1' },
      { title: '2 - The Receptive - 0', name: '2_-_The_Receptive_-_0', as: '/gallery/Nature_Morte/2_-_The_Receptive_-_0', ratio: '1:1' },
      { title: '5 - Nourishing While Waiting - 23', name: '5_-_Nourishing_While_Waiting_-_23', as: '/gallery/Nature_Morte/5_-_Nourishing_While_Waiting_-_23', ratio: '1:1' },
      { title: '18 - Decay - 38', name: '18_-_Decay_-_38', as: '/gallery/Nature_Morte/18_-_Decay_-_38', ratio: '1:1' },
      { title: '40 - Limitation - 10', name: '40_-_Limitation_-_10', as: '/gallery/Nature_Morte/40_-_Limitation_-_10', ratio: '1:1' },
      { title: '9 - Small Restraint - 55', name: '9_-_Small_Restraint_-_55', as: '/gallery/Nature_Morte/9_-_Small_Restraint_-_55', ratio: '1:1' },
      { title: '37 - Family - 53', name: '37_-_Family_-_53', as: '/gallery/Nature_Morte/37_-_Family_-_53', ratio: '1:1' },
      { title: '23 - Split Apart - 32', name: '23_-_Split_Apart_-_32', as: '/gallery/Nature_Morte/23_-_Split_Apart_-_32', ratio: '1:1' },
      { title: '46 - Pushing Upward - 6', name: '46_-_Pushing_Upward_-_6', as: '/gallery/Nature_Morte/46_-_Pushing_Upward_-_6', ratio: '1:1' },
      { title: '59 - Dispersion - 50', name: '59_-_Dispersion_-_50', as: '/gallery/Nature_Morte/59_-_Dispersion_-_50', ratio: '1:1' },
    ]
  },
  Starlight_Meadows: {
    collectionTitle: 'Starlight Meadows',
    collectionName: 'Starlight_Meadows',
    images: [
      { title: 'This Is Not An Abattoir', name: 'This_Is_Not_An_Abattoir', as: '/gallery/Starlight_Meadows/This_Is_Not_An_Abattoir', ratio: '3:2' },
      { title: 'Wait A Minute We’re the Good Guys?', name: 'Wait_A_Minute_Were_the_Good_Guys', as: '/gallery/Starlight_Meadows/Wait_A_Minute_Were_the_Good_Guys', ratio: '3:2' },
      { title: 'We Do Not Torture People', name: 'We_Do_Not_Torture_People', as: '/gallery/Starlight_Meadows/We_Do_Not_Torture_People', ratio: '3:2' },
      { title: 'Media Bias: Axis of Evil', name: 'Media_Bias_Axis_of_Evil', as: '/gallery/Starlight_Meadows/Media_Bias_Axis_of_Evil', ratio: '3:2' },
      { title: 'The King Is with Us Now', name: 'The_King_Is_with_Us_Now', as: '/gallery/Starlight_Meadows/The_King_Is_with_Us_Now', ratio: '3:2' },
      { title: 'Mr. Halloween', name: 'Mr_Halloween', as: '/gallery/Starlight_Meadows/Mr_Halloween', ratio: '3:2' },
      { title: 'On the Seventh of November', name: 'On_the_Seventh_of_November', as: '/gallery/Starlight_Meadows/On_the_Seventh_of_November', ratio: '3:2' },
      { title: 'Captured by the Pigs', name: 'Captured_by_the_Pigs', as: '/gallery/Starlight_Meadows/Captured_by_the_Pigs', ratio: '3:2' },
      { title: 'Guerilla Warfare', name: 'Guerilla_Warfare', as: '/gallery/Starlight_Meadows/Guerilla_Warfare', ratio: '3:2' },
      { title: 'A Life That Lasts a Day', name: 'A_Life_That_Lasts_a_Day', as: '/gallery/Starlight_Meadows/A_Life_That_Lasts_a_Day', ratio: '3:2' },
      { title: 'The Watchman', name: 'The_Watchman', as: '/gallery/Starlight_Meadows/The_Watchman', ratio: '3:2' },
      { title: 'Remember—Remember—The Seventh of November', name: 'Remember_Remember_The_Seventh_of_November', as: '/gallery/Starlight_Meadows/Remember_Remember_The_Seventh_of_November', ratio: '3:2' },
      { title: 'Yule', name: 'Yule', as: '/gallery/Starlight_Meadows/Yule', ratio: '3:2' },
      { title: 'He Is with Us but Remembers Nothing', name: 'He_Is_with_Us_but_Remembers_Nothing', as: '/gallery/Starlight_Meadows/He_Is_with_Us_but_Remembers_Nothing', ratio: '3:2' },
      { title: 'He Was Looking for a Way Out', name: 'He_Was_Looking_for_a_Way_Out', as: '/gallery/Starlight_Meadows/He_Was_Looking_for_a_Way_Out', ratio: '3:2' },
      { title: 'Troglodytes, They were Called', name: 'Troglodytes_They_were_Called', as: '/gallery/Starlight_Meadows/Troglodytes_They_were_Called', ratio: '3:2' },
      { title: 'That Old Chimp Called Himself Sarge', name: 'That_Old_Chimp_Called_Himself_Sarge', as: '/gallery/Starlight_Meadows/That_Old_Chimp_Called_Himself_Sarge', ratio: '3:2' },
      { title: 'You Didn’t—But, I Did.', name: 'You_Didnt_But_I_Did', as: '/gallery/Starlight_Meadows/You_Didnt_But_I_Did', ratio: '3:2' },
      { title: 'Behind the Barn', name: 'Behind_the_Barn', as: '/gallery/Starlight_Meadows/Behind_the_Barn', ratio: '3:2' },
      { title: 'That’s No Way to Play', name: 'Thats_No_Way_to_Play', as: '/gallery/Starlight_Meadows/Thats_No_Way_to_Play', ratio: '3:2' },
    ]
  }
}

export default collection
